In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1,2,3], [4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7,8,9], [10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [4]:
tensor1.requires_grad

False

In [5]:
tensor2.requires_grad

False

In [6]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [7]:
tensor1.requires_grad

True

In [8]:
print(tensor1.grad)

None


In [9]:
print(tensor1.grad_fn)

None


In [10]:
output_tensor = tensor1 * tensor2
output_tensor.requires_grad

True

In [11]:
print(output_tensor.grad)

None


c:\users\jonathan muñoz\appdata\local\programs\python\python37\lib\site-packages\torch\tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [12]:
print(output_tensor.grad_fn)

In [13]:
print(tensor1.grad_fn)

None


In [14]:
print(tensor2.grad_fn)

None


In [15]:
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn)

In [16]:
print(tensor1.grad)

None


In [17]:
output_tensor.backward()

In [18]:
print(tensor1.grad)

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [19]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [20]:
print(tensor2.grad)

None


In [21]:
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [22]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [24]:
with torch.no_grad():
    new_tensor = tensor1 * 3
    print('new_tensor = ', new_tensor)
    print('requires_grad for tensor = ', tensor1.requires_grad)
    print('requires_grad for tensor = ', tensor2.requires_grad)
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor =  True
requires_grad for tensor =  False
requires_grad for new_tensor =  False


In [25]:
def calculate(t):
    return t * 2

In [26]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [27]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [28]:
result_tensor.requires_grad

True

In [29]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [30]:
result_tensor_no_grad.requires_grad

False

In [31]:
tensor_one = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [34]:
tensor_two = torch.Tensor([[5, 6], [7, 8]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [35]:
tensor_one.requires_grad

True

In [36]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [37]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [38]:
print(tensor_one.grad)

None


In [39]:
print(tensor_two.grad)

None


In [40]:
final_tensor.backward()

In [42]:
print(tensor_one.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [43]:
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [44]:
detached_tensor = tensor_one.detach()
detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [45]:
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)