In [1]:
import torch
print(torch.__version__)

1.5.0+cpu


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
#torch.set_default_dtype(torch.int)

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

In [6]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [8]:
torch.numel(tensor_arr)

6

In [9]:
tensor_uninitialized = torch.Tensor(2, 2)
tensor_uninitialized

tensor([[ 0.0000e+00, 2.6447e+180],
        [ 4.1215e-33, 2.3587e+184]])

In [10]:
# Crear un tensor con valores randomicos
tensor_initialized = torch.rand(2, 2)
tensor_initialized

tensor([[0.6161, 0.1266],
        [0.3730, 0.1679]])

In [11]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [12]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [13]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

..\aten\src\ATen\native\TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [15]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [16]:
tensor_of_zeroes = torch.zeros_like(tensor_of_ones)
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [17]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
non_zero = torch.nonzero(tensor_eye)
non_zero

..\torch\csrc\utils\python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)


tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [19]:
i = torch.tensor([[0,1,1], [2,2,0]])
v = torch.tensor([3,4,5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i, v, [2,5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [20]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.0905, 0.9159, 0.1041],
        [0.7082, 0.0834, 0.8736]])

In [21]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [22]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [23]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [24]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [25]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [26]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [27]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [28]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [30]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3., 4., 5.])

torch.cat([tensor1, tensor2, tensor3], 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [31]:
# Indexing
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [32]:
random_tensor[0, 1]

tensor(8.)

In [33]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [34]:
random_tensor.size()

torch.Size([3, 3])

In [35]:
# Usa el mismo tensor y memoria
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [36]:
resized_tensor.size()

torch.Size([9])

In [37]:
random_tensor[2,2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [38]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [39]:
random_tensor.shape

torch.Size([3, 3])

In [40]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [42]:
tensor_unsqueeze.size()

torch.Size([3, 3, 1])

In [43]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [44]:
initial_tensor.size()

torch.Size([2, 3])

In [45]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [46]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [47]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [48]:
torch.cuda.is_available()

False