In [1]:
import torch
import torch.nn as nn

In [2]:
loss = nn.CrossEntropyLoss()

In [7]:
input = torch.randn(2, 1, requires_grad=True)
input

tensor([[0.4180],
        [1.1723]], requires_grad=True)

In [8]:
target = torch.empty(2, dtype=torch.long).random_(5)
target

tensor([0, 3])

In [5]:
output = loss(input, target)
output

tensor(2.2124, grad_fn=<NllLossBackward>)

In [ ]:
output.backward()

In [19]:
m = nn.Softmax(dim=1)

In [17]:
input = torch.randn(2, 3)
input

tensor([[ 0.4578,  0.2103,  1.0041],
        [-0.3848,  0.2623,  0.1703]])

In [20]:
output = m(input)
output

tensor([[0.2851, 0.2226, 0.4923],
        [0.2150, 0.4106, 0.3745]])

In [15]:
output.sum(axis=1)

tensor([1., 1.])